#ifndef ROBOTMAP_H
#define ROBOTMAP_H

#define LEFTMOTOR 2
#define RIGHTMOTOR 3

#define LAUNCHERMOTOR_ONE 4
#define LAUNCHERMOTOR_TWO 5

#define PUSHMOTOR 6
#define DROPMOTOR 7

#define CAMERA_PAN_MOTOR 8
#define CAMERA_TILT_MOTOR 9

#define LAUNCHER_ALWAYS_RUNNING 0
#define LAUNCHER_ON_LAUNCH 1
#define LAUNCHER_ON_JOYSTICK 2
#define LAUNCHER_ACTION LAUNCHER_ON_LAUNCH //change this
#endif
